<?php

namespace Database\Seeders;

use App\Models\Town;
use Illuminate\Database\Seeder;

class TownsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $towns=[
            ['id'=>1,'town'=>'Nairobi','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'47'],
            ['id'=>2,'town'=>'Mombasa','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'1'],
            ['id'=>3,'town'=>'Kisumu','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'42'],
            ['id'=>4,'town'=>'Nakuru','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'32'],
            ['id'=>5,'town'=>'Eldoret','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'27'],
            ['id'=>6,'town'=>'Kehancha','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'44'],
            ['id'=>7,'town'=>'Ruiru','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'22'],
            ['id'=>8,'town'=>'Kikuyu','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'22'],
            ['id'=>9,'town'=>'Kangundo','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'16'],
            ['id'=>10,'town'=>'Malindi','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'3'],
            ['id'=>11,'town'=>'Naivasha','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'32'],
            ['id'=>12,'town'=>'Kitui','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'15'],
            ['id'=>13,'town'=>'Machakos','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'16'],
            ['id'=>14,'town'=>'Thika','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'22'],
            ['id'=>15,'town'=>'Athi River','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'16'],
            ['id'=>16,'town'=>'Karuri','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'22'],
            ['id'=>17,'town'=>'Nyeri','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'19'],
            ['id'=>18,'town'=>'Kilifi','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'3'],
            ['id'=>19,'town'=>'Garissa','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'7'],
            ['id'=>20,'town'=>'Vihiga','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'38'],
            ['id'=>21,'town'=>'Mumias','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'37'],
            ['id'=>22,'town'=>'Bomet','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'36'],
            ['id'=>23,'town'=>'Molo','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'32'],
            ['id'=>24,'town'=>'Ngong','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'34'],
            ['id'=>25,'town'=>'Kitale','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'26'],
            ['id'=>26,'town'=>'Litein','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'35'],
            ['id'=>27,'town'=>'Limuru','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'22'],
            ['id'=>28,'town'=>'Kericho','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'35'],
            ['id'=>29,'town'=>'Kimilili','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'39'],
            ['id'=>30,'town'=>'Awasi','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'42'],
            ['id'=>31,'town'=>'Kakamega','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'37'],
            ['id'=>32,'town'=>'Kapsabet','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'29'],
            ['id'=>33,'town'=>'Mariakani','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'3'],
            ['id'=>34,'town'=>'Kiambu','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'22'],
            ['id'=>35,'town'=>'Mandera','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'9'],
            ['id'=>36,'town'=>'Nyamira','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'46'],
            ['id'=>37,'town'=>'Mwingi','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'15'],
            ['id'=>38,'town'=>'Kisii','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'45'],
            ['id'=>39,'town'=>'Wajir','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'8'],
            ['id'=>40,'town'=>'Rongo','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'44'],
            ['id'=>41,'town'=>'Bungoma','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'39'],
            ['id'=>42,'town'=>'Ahero','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'42'],
            ['id'=>43,'town'=>'Nandi Hills','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'26'],
            ['id'=>44,'town'=>'Makuyu','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'21'],
            ['id'=>45,'town'=>'Kapenguria','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'24'],
            ['id'=>46,'town'=>'Taveta','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'6'],
            ['id'=>47,'town'=>'Narok','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'33'],
            ['id'=>48,'town'=>'Ol Kalou','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'18'],
            ['id'=>49,'town'=>'Kakuma','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'23'],
            ['id'=>50,'town'=>'Webuye','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'39'],
            ['id'=>51,'town'=>'Malaba','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'40'],
            ['id'=>52,'town'=>'Mbita Point','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'43'],
            ['id'=>53,'town'=>'Ukunda','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'2'],
            ['id'=>54,'town'=>'Wundanyi','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'6'],
            ['id'=>55,'town'=>'Busia','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'40'],
            ['id'=>56,'town'=>'Runyenjes','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'14'],
            ['id'=>57,'town'=>'Migori','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'44'],
            ['id'=>58,'town'=>'Malava','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'37'],
            ['id'=>59,'town'=>'Suneka','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'45'],
            ['id'=>60,'town'=>'Embu','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'14'],
            ['id'=>61,'town'=>'Ogembo','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'45'],
            ['id'=>62,'town'=>'Hom Bay','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'43'],
            ['id'=>63,'town'=>'Londwar','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'23'],
            ['id'=>64,'town'=>'Kitengela','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'34'],
            ['id'=>65,'town'=>'Ukwala','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'41'],
            ['id'=>66,'town'=>'Keroka','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'45'],
            ['id'=>67,'town'=>'Meru','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'12'],
            ['id'=>68,'town'=>'Matuu','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'16'],
            ['id'=>69,'town'=>'Oyugis','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'42'],
            ['id'=>70,'town'=>'Nyahururu','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'31'],
            ['id'=>71,'town'=>'Kipkelion','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'35'],
            ['id'=>72,'town'=>'Luanda','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'38'],
            ['id'=>73,'town'=>'Nanyuki','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'31'],
            ['id'=>74,'town'=>'Maua','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'12'],
            ['id'=>75,'town'=>'Mtwapa','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'3'],
            ['id'=>76,'town'=>'Isiolo','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'11'],
            ['id'=>77,'town'=>'Eldama Ravine','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'30'],
            ['id'=>78,'town'=>'Voi','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'6'],
            ['id'=>79,'town'=>'Siaya','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'41'],
            ['id'=>80,'town'=>'Nyansiongo','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'46'],
            ['id'=>81,'town'=>'Londiani','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'35'],
            ['id'=>82,'town'=>'Iten/Tambach','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'28'],
            ['id'=>83,'town'=>'Chuka','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'13'],
            ['id'=>84,'town'=>'Malakisi','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'39'],
            ['id'=>85,'town'=>'Juja','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'22'],
            ['id'=>86,'town'=>'Ongata Rongai','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'35'],
            ['id'=>87,'town'=>'Bondo','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'41'],
            ['id'=>88,'town'=>'Moyale','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'10'],
            ['id'=>89,'town'=>'Maralal','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'25'],
            ['id'=>90,'town'=>'Gilgil','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'32'],
            ['id'=>91,'town'=>'Nambale','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'40'],
            ['id'=>92,'town'=>'Tabaka','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'45'],
            ['id'=>93,'town'=>'Muhoroni','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'42'],
            ['id'=>94,'town'=>'Kerugoya/Kutus','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'20'],
            ['id'=>95,'town'=>'Ugunja','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'41'],
            ['id'=>96,'town'=>'Yala','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'41'],
            ['id'=>97,'town'=>'Rumuruti','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'31'],
            ['id'=>98,'town'=>'Burnt Forest','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'27'],
            ['id'=>99,'town'=>'Maragua','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'21'],
            ['id'=>100,'town'=>'Kendu Bay','pickuppoint'=>'pickpoint_a1','shipping_charges'=>'1','county_id'=>'43']
        ];
        Town::insert($towns);
    }
}
